version: 0.2

phases:
  install:
    commands:
      - python --version
      - pip install -U -r requirements.txt
      - sh ubuntuinstallations.sh
  build:
    commands:
      - robot TestCase.robot
